# Generated by Django 4.0 on 2024-07-11 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0003_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='photo',
            field=models.URLField(blank=True, null=True, verbose_name='Rasm url'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='photo',
            field=models.URLField(blank=True, null=True, verbose_name='Rasm url'),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.URLField(blank=True, null=True, verbose_name='Rasm url'),
        ),
    ]
