# Generated by Django 4.0 on 2024-07-11 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0004_category_photo_subcategory_photo_alter_product_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='product',
            name='subcategory',
        ),
        migrations.AddField(
            model_name='category',
            name='category_icon',
            field=models.URLField(blank=True, null=True, verbose_name='Kategoriya iconi'),
        ),
        migrations.DeleteModel(
            name='Subcategory',
        ),
    ]
